name: Continuous Integration

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ '**' ]
    tags: [ v* ]

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17

      - name: Test Release g8
        run: sbt g8Test

      - name: Test Release
        run: sbt clean scalafmtCheckAll scalafmtSbtCheck
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:1.17
      - run: ls -a
      - run: sbt new file://../gatling-template.g8 --name=test --jdbcPlugin=yes --amqpPlugin=yes --kafkaPlugin=yes
      - run: ls -a
        working-directory: ./test
      - run: sbt clean scalafmtSbtCheck scalafmtCheckAll compile
        working-directory: ./test



